-- CreateEnum
CREATE TYPE "MessageType" AS ENUM ('TEXT', 'AUDIO', 'INTERACTIVE', 'SYSTEM');
CREATE TYPE "ConversationState" AS ENUM ('IDLE', 'BROWSING', 'CART', 'CHECKOUT_ADDRESS', 'CHECKOUT_DELIVERY', 'CHECKOUT_PAYMENT', 'CONFIRMATION_PENDING', 'ORDER_PLACED', 'CANCELLATION', 'HUMAN_HANDOFF');

CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "phoneNumber" TEXT NOT NULL UNIQUE,
  "preferredLang" TEXT,
  "state" "ConversationState" NOT NULL DEFAULT 'IDLE',
  "lastStateUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Message" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "type" "MessageType" NOT NULL,
  "language" TEXT,
  "rawPayload" JSONB NOT NULL,
  "normalizedText" TEXT,
  "direction" TEXT NOT NULL,
  CONSTRAINT "Message_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Transcript" (
  "id" TEXT PRIMARY KEY,
  "messageId" TEXT NOT NULL UNIQUE,
  "text" TEXT NOT NULL,
  "confidence" DOUBLE PRECISION,
  "durationSec" DOUBLE PRECISION,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Cart" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "currency" TEXT NOT NULL,
  "items" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Cart_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Order" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "cartId" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "totalAmount" DOUBLE PRECISION NOT NULL,
  "currency" TEXT NOT NULL,
  "address" JSONB NOT NULL,
  "deliveryOption" TEXT NOT NULL,
  "paymentMethod" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
